server:
  port: 8080

spring:
    datasource:
        url: jdbc:sqlite:db.sqlite  # SQLite 数据库文件路径
        driver-class-name: org.sqlite.JDBC  # SQLite 驱动

    jpa:
      database-platform: org.hibernate.community.dialect.SQLiteDialect  # 使用 SQLite 方言
      hibernate:
        ddl-auto: update  # 自动更新表结构（即当数据库是空的时候，自动创建表结构）
      show-sql: true  # 显示 SQL 语句

    web:
      resources:
        static-locations:
            - classpath:/static/
            - classpath:/public/
            - classpath:/resources/
            - classpath:/META-INF/resources/
            - classpath:/META-INF/resources/webjars/
            - file:dist/  # 用于前端构建后的静态资源

jwt:
  secret: secret